### ISSUE TITLE
Missing theme.config.json for default theme

### ISSUE THREAD

**Issue by Steeven9** [3d-dice/dice-box#105]
I just updated my library version to the latest one and there seems to be a breaking change: now also the default theme expects a `theme.config.json` file, even if the library doesn't provide one: 
- missing in https://github.com/3d-dice/dice-box/tree/main/public/assets/dice-box/themes/default
- missing in `node_modules`
- not added to `assets` when the library is installed from npm

The [getting started](https://fantasticdice.games/docs/usage/config#copy-static-assets) page also doesn't mention anything about this new requirement.

Version: 1.0.15 (which doesn't seem to be on GitHub?)

**Comment by Steeven9** [comment]
Update: even when trying to copy a config file from another theme such as [this one](https://github.com/3d-dice/dice-themes/blob/main/themes/blueGreenMetal/theme.config.json), I still get an error:

![image](https://github.com/3d-dice/dice-box/assets/25285679/8cea7e58-53b9-4449-850a-96f3743ac7bb)

**Comment by frankieali** [comment]
Thanks for reporting this. I'll look into it ASAP. I've been making some minor changes in preparations for `v1.1.0` but I must have introduced something that wasn't well tested yet.
The default config should not be required in the latest version.

**Comment by frankieali** [comment]
Looks like `postinstall` scripts no longer work on `npm`. That's a small problem.

**Comment by frankieali** [comment]
Oh no. Looks like code from the forthcoming `v1.1.0` made it into `v1.0.15`. I'll have to revert that out. The docs for `v1.1.0` are not ready yet.

**Comment by Steeven9** [comment]
Oh, that's good - I thought it was somewhat weird when I saw that 1.0.15 was not here on GitHub yet :D

1.0.14 works as before btw

**Comment by frankieali** [comment]
I'm planning to release `v1.1.0` later this week. I just need to wrap up the docs. I'll also see what I can do to provide a gracefully fallback to this issue to avoid the breaking change.

Also, looks like npm no longer runs `postinstall` script prompts or terminal output. I'll have to update the docs for that as well.

**Comment by frankieali** [comment]
Closed with the release of `v1.1`
