### ISSUE TITLE
New setup challenges, improve docs, swipe-to-roll possible?

### ISSUE THREAD

**Issue by bluepuma77** [3d-dice/dice-box#106]
Currently searching for a simple 3D dice roller to use in a Svelte web app with tablet touch, I really liked the simple 3D DICE ROLLER ([demo](https://sarahrosannabusch.github.io/dice/), [GitHub](https://github.com/sarahRosannaBusch/dice)) which can be triggered by a swipe, but the libs are totally outdated.

After some more research and digging into about 10 solutions, dice-box was the most promising from the looks, docs and being current. After getting the first dice to roll, I stumbled upon a few questions:

1. [Configuration option `id`](https://fantasticdice.games/docs/usage/config#configuration-options) -  is that a canvas I need to create before? That's what I was expecting. But instead the dice roll on a smaller canvas below the already created one. Or should I use `container` for a parent element the canvas is inserted into? In full size? Documentation is not clear.
2. [Theme Default Extras](https://fantasticdice.games/docs/themes/defaultExtras) - how is it loaded, all other themes provide a `string` to use, it seems to be missing here. 
3. Finally, is it possible to supply an initial vector for the roll from a swipe gesture, like direction and speed? That would be really nice 😃

**Comment by frankieali** [comment]
Hey @bluepuma77 . You did discover a documentation issue. The config option `id` should be `container`. I'll have to update that.

Here is a [demo using SvelteKit](https://codesandbox.io/p/devbox/sveltekit-3d-dice-extras-tmtmvg) I just put together on CodeSandbox. The `+page.svelte` shows how the box is configured and how to use CDN's to load the assets. This module does not work with SSR so I've turned it off in the `+page.ts` file.

I do not ship any CSS with Dice-Box, so it's up to you to size and place the canvas properly. The browsers default canvas size is 300px by 150px I think. Really small.

There is currently no feature to drag or swipe to roll. Sorry. Perhaps in the future.

Let me know if you have any other questions.

**Comment by bluepuma77** [comment]
@frankieali Thanks! Should I close the issue or leave it open for the swipe? 😃
