### ISSUE TITLE
Remove method does not work

### ISSUE THREAD

**Issue by frankieali** [3d-dice/dice-box#16]
When attempting to remove a die by passing in a die roll object I get `.filter() is not a method`. I understand why this is happening. Internally, all the dice rolls are cached in an object, indexed by their rollId. This is so they can be easily looked up once their roll value has been calculated after the physic simulation. However, when outputting the final results, this multidimensional object is converted into an array of objects. The rolls are not an array internally, so there is no .filter method.

This has also uncovered some other issues around data mutation in this project. I'm looking into how to better manage the data internally.

**Comment by clevett** [comment]
I don't know if it will help but I posted a draft PR to my library for Typescript: https://github.com/clevett/dice-box/pull/6/files

About half the work of converting the library to Typescript was fixing issues the data mutation.

**Comment by frankieali** [comment]
Fixed with version 0.6. I reworked both the `reroll` and `remove` methods so they will accept similar arguments and return similar data in their promises.
