### ISSUE TITLE
.roll() returns array of Die Result Objects

### ISSUE THREAD

**Issue by clevett** [3d-dice/dice-box#25]
When doing `const result = await dicebox.roll(notation);` the result is an array of  [Individual Die Result Object](https://fantasticdice.games/docs/usage/objects#individual-die-result-object) but documentation would indicate it should be [Roll Result Array Object](https://fantasticdice.games/docs/usage/objects#roll-result-array-object). I believe previously it was an array of Roll Results.

I've written a bunch of code to work around this but was curious was the expected behaviour is.

**Comment by frankieali** [comment]
That is correct. `roll`, `add`, `reroll` and `remove` methods return an array of Individual Die Result Objects. The `onRollComplete` callback returns the Roll Result Array Object.
However, if you know your dice have finished rolling (i.e.: Your `roll` promise was resolved) you can use `getRollResults` method to get the Roll Result Array Object.

**Comment by clevett** [comment]
I think you told me this before. ;) Awesome. I worked with that. :)
