### ISSUE TITLE
Unknown browser query `ie all`. Maybe you are using old Browserslist or made typo in query.

### ISSUE THREAD

**Issue by isabelbicalho** [3d-dice/dice-box#26]
Hello!

I downloaded kitchen sink code from demo https://codesandbox.io/s/3d-dice-demo-2bily5 
and I am trying to build it locally. I get this trouble, though.

Any solutions?

I'm on MAC

**Comment by isabelbicalho** [comment]
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@3d-dice/dice-box@0.6.0',
npm WARN EBADENGINE   required: { node: '>=14.15.0', npm: '6.14.x' },
npm WARN EBADENGINE   current: { node: 'v17.2.0', npm: '8.1.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@3d-dice/fdp@0.1.4',
npm WARN EBADENGINE   required: { node: '>=14.15.0', npm: '6.14.x' },
npm WARN EBADENGINE   current: { node: 'v17.2.0', npm: '8.1.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@3d-dice/fui@0.3.4',
npm WARN EBADENGINE   required: { node: '>=14.15.0', npm: '6.14.x' },
npm WARN EBADENGINE   current: { node: 'v17.2.0', npm: '8.1.4' }
npm WARN EBADENGINE }

**Comment by frankieali** [comment]
It might be the npm setting in package.json. It's explicitly wanting version 6.14.x
`"npm": "6.14.x"`
I'll update that to `"npm": ">=6.14.x"`.

**Comment by frankieali** [comment]
ok, I've removed the engines block all together. I don't think it's really necessary. I've just published updated versions for @3d-dice/dice-box, @3d-dice/FDP and @3d-dice/FUI. Hopefully they will work for you now.

**Comment by frankieali** [comment]
@isabelbicalho let me know if the updates worked and I'll close this issue.
