### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'nodeName')

### ISSUE THREAD

**Issue by DenchOriginal** [3d-dice/dice-box#27]
Hi, I have a Tauri application with Solid JS as framework and wanted to import and use your library. Something seems to be wrong because I get this error. But when I comment out the code, reload it and then release the code again it seems to initialize but then there are some WebAssembly Errors (could also be Tauri).

`const diceBox = new DiceBox("#dice-tray", {
        assetPath: '/assets/dice-box'
      })

    console.log(diceBox)

    diceBox.init().then(()=>{
        diceBox.roll('2d20')
    })
    
    ...
    
    <div id='dice-tray' className="p-3 h-[36rem]" />
`

This comes up in the console before I comment it out etc.

![grafik](https://user-images.githubusercontent.com/25980316/162630973-6bd01e82-e6df-4878-be78-b2de3d82f37e.png)

**Comment by frankieali** [comment]
My only guess here is that the DOM is not ready before the DiceBox class is invoked. Perhaps put it inside a DOMContentLoaded event listener
```javascript
document.addEventListener("DOMContentLoaded",() => {
  const diceBox = new DiceBox("#dice-tray", {
    assetPath: '/assets/dice-box'
  })
  diceBox.init().then(()=>{
    diceBox.roll('2d20')
  })
})
```

**Comment by frankieali** [comment]
The web assembly errors could be caused by the ammo wasm file not being available in your static assets folder. If your static assets are at '/assets/dice-box' then the DiceBox module will expect the ammo wasm file to be at `/assets/dice-box/ammo/ammo.wasm.wasm`
