### ISSUE TITLE
Feature Request: Presetting Roll Outcomes

### ISSUE THREAD

**Issue by matthewfee** [3d-dice/dice-box#29]
I don't know if this would be possible, but it would be awesome if the die roll outcomes could be set in advance.

That would support using random numbers generated from "true random" APIs like random.org, rather than relying on the physics engine for outcomes.

**Comment by frankieali** [comment]
Hey @matthewfee. I've seen this done on unity programs before, but I'm not versed well enough in physics programming to force a specific die face up based on a pre-determined number and have it look natural at the same time. The physics themselves are already quite random and the dice start with a random rotation on all 3 axis at creation.

**Comment by matthewfee** [comment]
Ok, cool, that makes sense. Yes, it definitely seems really random with the physics, moreso than the default random in Javascript.
