### ISSUE TITLE
Graphics Issue on Mobile Devices

### ISSUE THREAD

**Issue by matthewfee** [3d-dice/dice-box#30]
I recently integrated this library into my [OSE Character Generator](https://bxcharacter.netlify.app/).

A couple of people have reached out indicating they are receiving a graphics error where dice look like the following:

![image](https://user-images.githubusercontent.com/60991158/165322821-86fb8af1-77d1-41f3-b484-7564ac9d2ab8.png)

user 1: iPhone 11, Chrome (Safari engine)
user 2: iPhone, Safari

I've also seen some delays when using the dice on Android, where sometimes it takes several seconds before the dice will show up.

Is this related to the browser compatibility for background Canvas? And any suggestions on how to fix this?

**Comment by frankieali** [comment]
@matthewfee any idea what iOS version the iPhone 11 was running? I'll start testing with 13.7. https://en.wikipedia.org/wiki/IPhone_11#Specifications

**Comment by matthewfee** [comment]
Just from my testing in Android, it looks like some of the dice are not rolling consistently.

Chrome dev tools _sometimes_ show the following error: 

```
dice-box.es.js:178 Uncaught TypeError: Cannot read properties of undefined (reading 'completedRolls')
    at WorldOffScreen.__privateGet.onRollResult (dice-box.es.js:178:7)
    at Worker.__privateGet.onmessage (world.offscreen.js:112:14)
```

Most often it's just the following

`No result. This die needs a reroll.`

The initial rolls are being triggered, but the dice don't show up. Usually waiting a bit (30 seconds or so) fixes the problem, which I guess means that it could be related to the time it takes for dice models to load.

**Comment by itlackey** [comment]
Any update on this? I have a few testers saying the dice do not work on iPhone at all

**Comment by frankieali** [comment]
This issue seems to be a limitation of the browser version and device hardware (outdated or unsupported webgl features). I looked into ways to make the 3D engine more compatible with older hardware but was unable to find a work around.
