### ISSUE TITLE
Cannot find module 'copy-dir' on npm install

### ISSUE THREAD

**Issue by Apexal** [3d-dice/dice-box#41]
Firstly, thanks for creating this project! It's exactly what I was looking for.

When I run `npm install @3d-dice/dice-box` with the latest verison I get the following error (the rest of the lines are removed for brevity)

```
npm ERR! code 1
npm ERR! path /home/frank/Projects/ddtools-web/frontend/node_modules/@3d-dice/dice-box
npm ERR! command failed
npm ERR! command sh -c node copyAssets.js
npm ERR! node:internal/modules/cjs/loader:942
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module 'copy-dir'
npm ERR! Require stack:
npm ERR! - /home/frank/Projects/ddtools-web/frontend/node_modules/@3d-dice/dice-box/copyAssets.js
```

As far as I can tell, it undoes installing the whole package upon this error so I can't ignore it and simply copy over the file myself.

I experimented a bit by forking and moving `copy-dir` from `devDependencies` to `dependencies` but then get another dependency error about `node-abort-controller`.

Should these two packages be listed in `dependencies`?

**Comment by frankieali** [comment]
Thanks for reporting this @Apexal. I'll look into it right away. I probably didn't test this as much as I should have.

**Comment by frankieali** [comment]
Yup, you were right. Moving the file copy packages from "dev-dependencies" to "dependencies" seems to have fixed the problem. @3d-dice/dice-box version bumped to 1.0.2

**Comment by Apexal** [comment]
Awesome! Just added it to my project and it works and looks great. Thank you again for maintaining this.
