### ISSUE TITLE
Integrate into existing react-three-fiber/threejs world?

### ISSUE THREAD

**Issue by Heilemann** [3d-dice/dice-box#46]
I have an existing 3D world built in react-three-fiber (so threejs under the hood). This wouldn't integrate into that, right? I don't know Babylon, but at a glance it seems entirely unrelated?

**Comment by frankieali** [comment]
Well, they could work together, but they would have to run on separate canvases. So they wouldn't be truly integrated. 
I recommend [Dice So Nice](https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/tree/master) for three.js projects. Dice So Nice was built for [Foundry Virtual Table Top](https://foundryvtt.com/) so it's not a simple drop in module, but the code for the dice runs on three.js and is originally based on [teal dice](http://a.teall.info/dice/).

**Comment by frankieali** [comment]
You could try this library as well https://github.com/MajorVictory/3DDiceRoller
Demo at http://dnd.majorsplace.com/dice/index.html
