### ISSUE TITLE
Next JS Support

### ISSUE THREAD

**Issue by marvink** [3d-dice/dice-box#49]
Hi Frank,

fantastic job so far. I tried to use your script in a nextjs scenario and i had issues regarding the type of module that you use. Maybe you can have a way to export the module in different rollup formats so that i can use them with nextjs :-)

I also saw that you are using location or document. This is probably also an issue with nextjs framework.

Cheers

**Comment by marvink** [comment]
Nevermind, i got it working.

**Comment by arrisar** [comment]
Would you mind sharing more detail about the issue and the fix involved? Want to be sure I'm not duplicating issues if you've already got a fix.

**Comment by marvink** [comment]
Lately i managed to get it working with dynamic imports without recompiling it. So if you use dynamic imports and bring it work that the overall dicebox is only rendered once it should work as expected.

**Comment by clevett** [comment]
> Lately i managed to get it working with dynamic imports without recompiling it. So if you use dynamic imports and bring it work that the overall dicebox is only rendered once it should work as expected.

Could you provide an example? I'm trying to get this working and running into the same issues.

**Comment by moficodes** [comment]
@clevett @marvink 

Any chance you can share how this worked in Nextjs?
