### ISSUE TITLE
Unable to get code to run

### ISSUE THREAD

**Issue by UsAndRufus** [3d-dice/dice-box#50]
Hi there! Love the library. Unfortunately, I'm unable to get anything to run.

I tried downloading a zip of the [Getting Started demo](https://codesandbox.io/s/3d-dice-demo-v1-0-2-sm4ien?file=/package.json), but when running `npm start` I get 
```
C:\Users\rufus\WebstormProjects\3d-dice-demo-v105\node_modules\@3d-dice\dice-box\dist\dice-box.es.js: Unknown browser query `not ie all`. Maybe you are using old Browserslist or made typo in query.
```

So I tried making my own simple app, see below for for code. It seems to compile fine, but then when running I get this issue:
![image](https://user-images.githubusercontent.com/4115329/179314941-d143cb5d-5ba0-4e98-9ea9-367af30b3a70.png)

Looks like Parcel isn't set up for serving pre-compile WASM files? I tried to find an answer, and looked through some other build system docs, but couldn't find anything. FWIW, I tried with `esbuild` as well and got the same issue.

An example app that works out of the box would go a long way! let me know if I can help in any way. Thanks!

## Example app

```index.js
import DiceBox from '@3d-dice/dice-box'

document.addEventListener("DOMContentLoaded", async () => {
    console.log('hello')
    const diceBox = new DiceBox("#dice-box", {
        assetPath: '/public/assets/dice-box/', // include the trailing backslash.
        theme: 'default'
    })

    diceBox.init().then(()=>{
        diceBox.roll('2d20')
    })
})
```

```index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
</head>
<body>
<h1>yooooo</h1>
<div id="dice-box">
    <script type="module" src="index.js"></script>
</div>
</body>
</html>
```

```package.json
{
{
  "scripts": {
    "start": "parcel src/index.html --open",
    "build": "parcel build src/index.html"
  },
  "dependencies": {
    "@3d-dice/dice-box": "^1.0.5"
  },
  "devDependencies": {
    "parcel": "^2.6.2",
    "@babel/core": "7.2.0",
    "typescript": "4.4.4"
  },
  "resolutions": {
    "@babel/preset-env": "7.13.8"
  }
}

```

NB don't think I need all of those dependencies in there - was just adding extra dependencies from the examples to see if they were needed.

**Comment by frankieali** [comment]
Starting with the basics, do you have the `ammo.wasm.wasm` file available at `/public/assets/dice-box/ammo/` folder? The second error states that it is unable to find this file. I don't believe this is a Parcel compile issue. It's probably a server configuration issue.

**Comment by UsAndRufus** [comment]
Yep, I had the `ammo.wasm.wasm` file in that folder, with that folder setup when I ran the app. Am I missing some Parcel config to let those files be served? I wonder if it stems from strict security rules in the browser (I tried Chrome and Firefox and it didn't work in either though)

**Comment by frankieali** [comment]
For my apps I've been using vite and I'm not deeply familiar with parcel. However I was able to get a basic example to work. It just seems that parcel is not copying the public assets to the dist folder. You may want to look into [parcel-plugin-static-files-copy](https://github.com/elwin013/parcel-plugin-static-files-copy) plugin to resolve that. I just manually copied them to the `dist` folder and things started working. Note that in Firefox the canvas has a width and height of 0 so you'll need to add some minimal styles to make the canvas visible.

I found some related info in this parcel thread [How to serve static files?](https://github.com/parcel-bundler/parcel/issues/1080#issuecomment-584745016)

I hope that helps.

**Comment by frankieali** [comment]
I also noticed in the docs that Parcel says to run the dev server using `npx parcel src/index.html`. I used `npm start` and I could see the `dist` folder produced by the build. I think using npx might hide the dist folder.

**Comment by UsAndRufus** [comment]
Thanks so much! Will take a look when I get time. For the future, a working downloadable example would be really helpful :)

**Comment by frankieali** [comment]
Hope it works. Examples are available on [Code Sandbox](https://codesandbox.io/s/3d-dice-demo-v1-0-5-sm4ien). More links on this project's landing page, but I don't have time right now to do integration examples for various front-end frameworks.

**Comment by arranf** [comment]
I ran into the same issues with Parcel - using Vite this isn't an issue.

I believe it's because Parcel doesn't use the right mime-type when serving the `.wasm` file
