### ISSUE TITLE
Feature addition request

### ISSUE THREAD

**Issue by rahul70392** [3d-dice/dice-box#61]
I am working on a dice game in which the user can randomly place(drag and drop) a solid box on the board and then roll the dice. The dice would collide with those solid boxes and it would affect the dice results. Can you help me building this module.

**Comment by rahul70392** [comment]
There is - https://github.com/schteppe/cannon.js for three.js library. Can we have something similar?

**Comment by frankieali** [comment]
I've been working on this dice box version [@3d-dice/dice-box-threejs](https://github.com/3d-dice/dice-box-threejs). It's based on threeJS and [cannon-es](https://github.com/pmndrs/cannon-es)

**Comment by guaxinimdmx** [comment]
Very cool, is there a way to force the result of the dice? Showing only the animation?

**Comment by frankieali** [comment]
See predetermined-outcomes - https://github.com/3d-dice/dice-box-threejs#predetermined-outcomes
