### ISSUE TITLE
1d100 adds the d10 when result is 10

### ISSUE THREAD

**Issue by clevett** [3d-dice/dice-box#66]
When rolling 1d100 on a result of 10 on the d10 it is added to the d100 result.

Using the code based on the React Demo. Includes dicebox + parser.

Percentile dice = consist of two d10s, one labeled with every single-digit number 0-9, (Ones dice - or unit die) the other labeled for the tens place, so 00-90 (Tens dice - or ten die).

Expected behavior is the d10 is treated as a 0 on a roll of 10 when rolled as part of a d100. So 10 + 60 = 60, not 70.

![Screenshot 2023-01-25 204720](https://user-images.githubusercontent.com/10157460/214691544-2a9df95a-152e-4211-9e33-f8ac86262162.png)

**Comment by clevett** [comment]
I found the issue. In [colliderFaceMap](https://github.com/3d-dice/dice-box/blob/main/public/assets/dice-box/models/default.json), the  d10 has two sides that map to 10 instead of 0.

**Comment by frankieali** [comment]
Yup. You're right on that one. I've been using the 'dice or rolling' theme so much lately that I didn't notice this issue on the default dice. On the 'dice of rolling' theme, the [numbers are correctly set](https://github.com/3d-dice/dice-themes/blob/main/themes/diceOfRolling/smoothDice.json#L621). 
I'll be sure to fix this. Thanks for bringing it up.

**Comment by clevett** [comment]
@frankieali We commissioned a new D10 model. I will send it to you. :)
