### ISSUE TITLE
Disabling shadows adds a white background to the dice box

### ISSUE THREAD

**Issue by ZeAntwan** [3d-dice/dice-box#68]
Hi, and thanks for creating this tool!
I was trying to implement it in a way for me to overlay on top of a live stream, without the shadows to match the aesthetics.

But after messing around with it for a while I realised that if I set the option "enableShadows: false:, I lose the shadow, but also the transparent background, meaning even if I don't want a background, or want an image, it gets replaced by a white fill.
![image](https://user-images.githubusercontent.com/11023019/215057680-14a5eaec-47f4-4a26-b093-18814cae589d.png)
![image](https://user-images.githubusercontent.com/11023019/215057731-8bd822d8-6254-44ca-963a-92fa9c124869.png)

**Comment by frankieali** [comment]
Yes. There is certainly something going wrong there. I'm seeing the issue in all the demos. I recently updated the BabylonJS module. Something might have changed concerning shadows or transparent canvas. I'll look into it.

**Comment by frankieali** [comment]
The problem was related to changes in BabylonJS. Fixed in version 1.0.11
