### ISSUE TITLE
clear is not a function

### ISSUE THREAD

**Issue by marvink** [3d-dice/dice-box#73]
I have trying to rebuild my current JS implementation to typescript. 
Now i have faced an issue on the world 
![grafik](https://user-images.githubusercontent.com/1224526/220757885-63295fb4-9862-4f5f-a51c-5b33a9caf34f.png)

If i am not mistaking this is referencing to the following line:
https://github.com/3d-dice/dice-box/blob/759b885544cb11291583ca03220b155187c92937/src/WorldFacade.js#L369

I need to be honest that i wasn't able to understand the code at this place. 
My hope was that you have an instant idea.

**Comment by marvink** [comment]
Arg.... the issue was simple. It seems the world was not initialized due to a race condition.

**Comment by squiter** [comment]
Sorry to reopen this, but how did you fix this problem?
I'm getting this error as well

**Comment by Heilemann** [comment]
@marvink I have the same problem, do you remember the exact solve?
