### ISSUE TITLE
dice replay the same result

### ISSUE THREAD

**Issue by OoWoodOne** [3d-dice/dice-box#75]
I don't know if it is possible to achieve the replay function of the dice?
Some originally random values can be fixed, so that the results of the cast are also fixed.
Application scenarios such as multiplayer games, player 1's dice results can be reproduced in player 2.

**Comment by frankieali** [comment]
Try this version. It's a rough implementation but it works. https://github.com/3d-dice/dice-box-threejs. Demo here: https://codesandbox.io/s/dice-box-threejs-j79h35?file=/src/index.js

**Comment by julbh** [comment]
This is perfect module. Now I want to manually set the value of each dices before rolling.
Like this: {value: 3, sides: 6, themeColor: "#354243"}

https://codesandbox.io/s/dice-box-threejs-j79h35?file=/src/index.js
It doesn't work in current npm module(1.0.8) with React JS 18.
When can we expect a new version?

Looking forward to a new version.
Thank you.
