### ISSUE TITLE
Show dots instead of digits ?

### ISSUE THREAD

**Issue by craze3** [3d-dice/dice-box#84]
Hey @frankieali, is there any way to display dots on the dice, instead of digits ? I want a traditional style 6 sided dice with dots on it 🎲 Would this he achievable with a custom theme? Thanks in advance!

**Comment by frankieali** [comment]
Yes, this is achievable with a custom theme. I was just looking through the @3d-dice/dice-themes and realized that I never posted a custom theme I made for Fate dice. I'll QC it to make sure it's good to post. If so then it's not a complicated task to add a d6 with pips.

**Comment by frankieali** [comment]
Added to [dice-themes](https://github.com/3d-dice/dice-themes/tree/main/themes). Available in `default-extended` and `smooth-pip`. The die name is `pip` and to roll it you would specify `4dpip`.
