### ISSUE TITLE
Can I set Result Before Roll?

### ISSUE THREAD

**Issue by UtariD86** [3d-dice/dice-box#86]
Before throwing the dice, I want to send values into it with my own random number generation method and the dice will turn out in accordance with these values. In this way, I can generate numbers in different ways and display the results to the user accordingly. I can also shorten the waiting time by starting the transactions I linked to the dice earlier. How do I send these values to the dice? How do I get these values to come up visually?

**Comment by frankieali** [comment]
What you're asking for is "deterministic rolling". There have been a couple of issue posts concerning this feature already. See https://github.com/3d-dice/dice-box/issues/47#issuecomment-1251300532
