### ISSUE TITLE
Mobile support for 3d simulation suspended.

### ISSUE THREAD

**Issue by watcherdm** [3d-dice/dice-box#87]
Currently, suspending the 3D simulation doesn't allow this library to work on mobile as it still tries to load the WebGL context and the WASM code. It would be ideal if this library provided a delicate fallback: "the world doesn't support fancy 3D things; let's just generate random numbers and return the expected result shape."

**Comment by frankieali** [comment]
Hey. Great to hear that the dice are rolling now. I bumped the module dependencies for BabylonJS, the underlying 3D rendering engine. I guess that may have fixed some webGL rendering issue. I think shadows were also causing some rendering issue that were also fixed. Either way, glad things are working. I'm going to close this issue.
