### ISSUE TITLE
Dice canvas is small and in the top-left corner

### ISSUE THREAD

**Issue by robinzimmermann** [3d-dice/dice-box#89]
I am trying out this library. I think I followed the directions in the readme. Functionally it works, but for some reason the dice are really small and only show in the top-left corner. I've attached a screenshot:

![dice](https://github.com/3d-dice/dice-box/assets/725660/182b6e48-c8e4-4241-a7ea-6b1dcdba4b53)

The area in the dashed lines seems to be the canvas.  I have the height and width at 100%, as the demo says.

I tried copying the code from https://codesandbox.io/s/3d-dice-demo-v1-0-2-sm4ien?file=/src/styles.css:6-596 and it still happens.

Now, I am running this inside a Vue application, but I didn't think it should make a difference. I'm mentioning it just in case it does.

**Comment by frankieali4** [comment]
It could be that a wrapping element is not at 100%. In the CSS the canvas element is set by it's ID `#dice-box canvas`. I would check that your html element has the id `<div id="dice-box"></div>`
It could also be that the script is executing before the DOM is ready. Try moving your script tag to the bottom of the `.html` page or adding the [defer attribute](https://www.w3schools.com/tags/att_script_defer.asp) to the script tag
I haven't used Vue a lot, but I could trying setting up a sandbox. Are you using Vite's Vue template to set up a basic project?

**Comment by robinzimmermann** [comment]
OMG you are a friggin' genius! I would never have come up with that fix! Even with the answer I don't know how you figured it out!

Just to say it clearly, your fix worked and this ticket can be closed. Although perhaps the documentation could be updated for this case?

**Comment by robinzimmermann** [comment]
I'm not sure what the rules for closing are, but if this ticket doesn't get closed shortly, then I'll close it.

**Comment by herbig** [comment]
Hey @frankieali4 I'm experiencing the same issue, but in a React project.  I followed this example:

https://codesandbox.io/p/sandbox/react-roller-attributes-v1-0-5-65uqhv?file=%2Fsrc%2FApp.js%3A48%2C9

<img width="481" alt="Screenshot 2024-03-18 at 10 51 41 PM" src="https://github.com/3d-dice/dice-box/assets/384559/7fa311ca-7420-4e7e-b7b6-26dcd38f71e6">

I've got the dice scale dialed way up for this, and added the box to show where it can land.  My body looks like this:

```
  <body style="position: relative;">
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    <div id="dice-box" style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; pointer-events: none;"></div>
  </body>
  ```

Any ideas would be great, I'm loving this library and excited to make use of it!
