### ISSUE TITLE
Indexing an array with createUUID

### ISSUE THREAD

**Issue by clevett** [3d-dice/dice-box#9]
In world.offscreen.js, pendingThemPromises is declared as an array. The loadTheme function tries index the array with a string but arrays are index by numbers. Has this been working ?

`pendingThemePromises: = []`

```
	async loadTheme(theme: string) {
		const id = createUUID()

		return new Promise((resolve, reject) => {
			this.#OffscreenWorker.postMessage({action: "loadTheme", id, theme})
			this.pendingThemePromises[id] = resolve
		})
	}
```

**Comment by frankieali** [comment]
Yes, you're correct. In this instance it seems I'm adding properties to an Array object. Not the proper use of an Array at all. Its length will still be zero. However, since I only reference the properties in code and never try to loop over `pendingThemePromises` everything still works.

**Comment by clevett** [comment]
To resolve the Typescript error, I rewrote this like this

```
case "theme-loaded":
 const findPromise = this.pendingThemePromises.find((obj) => obj.id === e.data.id)
 findPromise?.promise()
 break;

```

```
	async loadTheme(theme: string) {
		const id = createUUID()

		return new Promise((resolve, reject) => {
			this.#OffscreenWorker.postMessage({action: "loadTheme", id, theme})
			this.pendingThemePromises.push({
				id,
				promise: resolve
			})
		})
	}
```

**Comment by frankieali** [comment]
Themes have been completely reworked for version 1.0. This issue is now n/a.
