### ISSUE TITLE
Define theme/themeColor for a specific dice.

### ISSUE THREAD

**Issue by 01taylop** [3d-dice/dice-box#93]
What is the recommended approach to support a different theme or themeColor for the same type of dice? For example, to have two six-sided dice, one red and one blue.

It looks like themeColor does not currently support this use case, but might be the preferred solution. Perhaps passing in the theme colour from the config.

Alternatively, some themes use different colours for different dice, but solving this issue at the theme level would likely introduce complexity into what is a clean theming solution.

I'm curious if this use-case is supported, or has been considered as a future enhancement.

**Comment by frankieali** [comment]
These sandboxes might help you.
[Multiple dice - different colors](https://codesandbox.io/p/sandbox/dice-colors-tk2vpc?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsw1dnnc00063b6hnrtiqrrc%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsw1dnnc00023b6h9bj4akma%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsw1dnnc00033b6h0f1v82n5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsw1dnnc00053b6hjue7gch2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsw1dnnc00023b6h9bj4akma%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsw1dnnc00013b6hlu89m74w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clsw1dnnc00023b6h9bj4akma%2522%252C%2522activeTabId%2522%253A%2522clsw1dnnc00013b6hlu89m74w%2522%257D%252C%2522clsw1dnnc00053b6hjue7gch2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsw1dnnc00043b6hg8nxuijj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsw1dnnc00053b6hjue7gch2%2522%252C%2522activeTabId%2522%253A%2522clsw1dnnc00043b6hg8nxuijj%2522%257D%252C%2522clsw1dnnc00033b6h0f1v82n5%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsw1dnnc00033b6h0f1v82n5%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
[Every roll a new color](https://codesandbox.io/p/sandbox/dice-es6-module-cdn-lhbs99?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqzbzts700063b6gtwn6xgvx%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqzbzts700023b6g6vcw15hp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqzbzts700033b6g9jzf4diw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqzbzts700053b6gy7b707sv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqzbzts700023b6g6vcw15hp%2522%253A%257B%2522id%2522%253A%2522clqzbzts700023b6g6vcw15hp%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clqzbzts700053b6gy7b707sv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqzbzts700043b6gtgdalbp8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqzbzts700053b6gy7b707sv%2522%252C%2522activeTabId%2522%253A%2522clqzbzts700043b6gtgdalbp8%2522%257D%252C%2522clqzbzts700033b6g9jzf4diw%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqzbzts700033b6g9jzf4diw%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by 01taylop** [comment]
That's exactly what I was looking for, thank you so much.

How do you prefer to proceed with this raised issue? Would you like to close it, or should these Sandbox links be added into the documentation.

More than happy to raise a draft PR once I familiarise myself with the contributing guide.

**Comment by frankieali** [comment]
Great! Glad to hear it's working for you. I'll close this issue. I have quite a number of sandbox demos now. I should probably add links to them all in the docs.
