### ISSUE TITLE
Multi-colored dice?

### ISSUE THREAD

**Issue by jimshoop** [3d-dice/dice-box#98]
Great work on this! Hoping there's a way to have colors applied per die. I see the themeColor on the roll method but this seems to apply to the entire group. Is there a way to set each die color individually?

**Comment by frankieali** [comment]
There are two ways to accomplish multiple colors. You can `.add()` to a roll or you can define a roll array. Here's a demo: https://codesandbox.io/p/sandbox/dice-colors-tk2vpc

Hope that helps.

**Comment by jimshoop** [comment]
This is really helpful. Thank you. Love this roller!
