### ISSUE TITLE
wasm streaming compile failed

### ISSUE THREAD

**Issue by jimshoop** [3d-dice/dice-box#99]
This error shows in the console but the roller seems to be working fine. Is this a config or compile error on my part or something intrinsic to chrome? I'm using webpack.

wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

**Comment by frankieali** [comment]
That looks like a server config issue. If you are serving the `ammo.wasm.wasm` file then you need to assure the header for `Content-Type:` is set to `application/wasm` and not text.

**Comment by jimshoop** [comment]
Thank you. I noticed it isn't having the issue on the prod server, just my local dev. I'll look into it.
